- hosts: all
  tasks:

  - name: selinux disabled
    when: "'centos' in inventory_hostname"
    selinux:
      state: "{{ selinux_state }}"
      

  - name: Install Apache
    package:
      name: "{{ apache }}"
      state: present
  
  - name: Start Apache service 
    systemd:
      state: started
      enabled: yes
      name: "{{ apache }}"
  
  - name: Download temaplate
    get_url: 
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/little-fashion.zip
      dest: /tmp/little-fashion.zip

  - name: Install Unzip
    package: 
      name: unzip
      state: latest