- hosts: all
  tasks:

  - name: selinux disabled
    when: "'centos' in inventory_hostname"
    selinux:
      state: "{{ selinux_state }}"
      

  - name: Install Apache
    package:
      name: "{{ apache }}"
      state: present
  
  - name: Start Apache service 
    systemd:
      state: started
      enabled: yes
      name: "{{ apache }}"