- hosts: all
  tasks:

  - name: selinux disabled
    when: "'centos' in inventory_hostname"
    selinux:
      state: "{{ selinux_state }}"
      

  - name: Install Apache
    package:
      name: "{{ apache }}"
      state: present
  
  - name: Start Apache service 
    systemd:
      state: started
      enabled: yes
      name: "{{ apache }}"
  
  - name: Download temaplate
    get_url: 
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/little-fashion.zip
      dest: /tmp/little-fashion.zip

  - name: Install Unzip
    package: 
      name: unzip
      state: latest
  
  - name: Unzip template
    unarchive:
      src: /tmp/little-fashion.zip
      dest: /tmp
      remote_src: yes

  - name: Move template to the html folder
    shell: mv /tmp/2127_little_fashion/* /var/www/html/
    args:
      creates: /var/www/html/index.html
      